[package]
name = "zinc"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
crypto-bigint = "0.5.5"
num-bigint = "0.4.6"
zeroize = "1.8.1"


[features]
default = []
asm = []