[package]
name = "zinc"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
criterion = "0.5.1"
crypto-bigint = "0.5.5"
displaydoc = "0.2.5"
hashbrown = "0.15.2"
num-bigint = "0.4.6"
sha3 = "0.10.8"
thiserror = "2.0.11"
zeroize = "1.8.1"


[features]
default = []
asm = ["sha3/asm"]

[[bench]]
name = "random_field_benches"
harness = false
