name: Build and test code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.88
    steps:
      - uses: actions/checkout@v4

      - name: Build all targets
        run: cargo test --workspace --no-run

      - name: Run library tests
        run: cargo test --workspace --lib

      - name: Run documentation tests
        run: cargo test --workspace --doc
