name: Coverage (Push)

on:
  push:
    branches: ['**']  # all branches, including main

permissions:
  contents: read
  actions: write

jobs:
  coverage-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cargo install cargo-llvm-cov
      - run: cargo llvm-cov --workspace --lcov --output-path lcov.info --ignore-filename-regex '^examples/'

      - name: Upload branch coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: lcov.info
          retention-days: 21
