name: Linter check

on: push

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  linter_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Fmt
        run: rustup component add --toolchain nightly-2024-11-05-x86_64-unknown-linux-gnu rustfmt

      - name: Run Fmt
        run: cargo fmt --all -- --check

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Check typos
        uses: crate-ci/typos@master