name: Spell Check
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use typos with config file
        uses: crate-ci/typos@master
        with:
          config: .github/workflows/typos.toml
